apiVersion: v1
kind: Secret

metadata:
  name: app-secret
  namespace: skillzverse

type: Opaque

stringData:
  MYSQL_DATABASE: skillzverse
  MYSQL_USER: skillzuser
  MYSQL_PASSWORD: StrongPassword123
  MYSQL_ROOT_PASSWORD: RootPassword123
