apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: skillzverse

spec:
  replicas: 6

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:

      imagePullSecrets:
      - name: dockerhub-secret

      containers:

      - name: backend

        image: saihari1/skillzverse:server

        imagePullPolicy: Always

        ports:
        - containerPort: 8090

        env:

        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_URL

        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: MYSQL_USER

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: MYSQL_PASSWORD
